development:
  GMAIL_USERNAME: framgia.bangladesh
  GMAIL_PASSWORD: mannamanna
test:
  GMAIL_USERNAME: framgia.bangladesh
  GMAIL_PASSWORD: mannamanna
production:
  GMAIL_USERNAME: framgia.bangladesh
  GMAIL_PASSWORD: mannamanna
